#!/usr/bin/env sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the &quot;License&quot;);
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an &quot;AS IS&quot; BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, then to run this script, type that shell and then run the script.
#       For example, ksh gradlew.
#   (2) You need the 'java' executable on your PATH.
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%/*}
    [ $APP_HOME = &quot;$app_path&quot; ] &amp;&amp; [ $APP_HOME != &quot;/&quot; ]
do
  app_path=$APP_HOME
done

# Make it absolute
if [ &quot;$APP_HOME&quot; != &quot;/&quot; ]
then
  cd &quot;$APP_HOME&quot;
  APP_HOME=`pwd`
fi

APP_NAME=&quot;Gradle&quot;
APP_BASE_NAME=`basename &quot;$0&quot;`

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS=&quot;&quot;

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo &quot;$*&quot;
}
die () {
    echo
    echo &quot;$*&quot;
    echo
    exit 1
}
# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case &quot;$(uname)&quot; in
  CYGWIN* )
    cygwin=true
    ;;
  Darwin* )
    darwin=true
    ;;
  MINGW* )
    msys=true
    ;;
  NONSTOP* )
    nonstop=true
    ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

# Determine the Java command to use to start the JVM.
if [ -n &quot;$JAVA_HOME&quot; ] ; then
    if [ -x &quot;$JAVA_HOME/jre/sh/java&quot; ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x &quot;$JAVACMD&quot; ] ; then
        die $JAVA_HOME/bin/java is not executable
    fi
else
    JAVACMD=java
    which java &gt;/dev/null 2&gt;&amp;1 || die java command not found
fi

# Increase the maximum file descriptors if we can.
if [ &quot;$cygwin&quot; = &quot;false&quot; -a &quot;$darwin&quot; = &quot;false&quot; -a &quot;$nonstop&quot; = &quot;false&quot; ] ; then
    MAX_FD_LIMIT=`ulimit -H -n`
    if [ $? -eq 0 ] ; then
        if [ $MAX_FD -ne maximum -a $MAX_FD -gt $MAX_FD_LIMIT ] ; then
            warn &quot;max file descriptors $MAX_FD_LIMIT cannot be surpassed, setting to $MAX_FD_LIMIT&quot;
            MAX_FD=$MAX_FD_LIMIT
        fi
        ulimit -n $MAX_FD
        if [ $? -ne 0 ] ; then
            warn &quot;Could not set maximum file descriptor limit to $MAX_FD&quot;
        fi
    else
        warn &quot;Could not query maximum file descriptor limit: $MAX_FD_LIMIT&quot;
    fi
fi

# For Darwin, add options to specify how the application appears in the dock
if $darwin; then
    GRADLE_OPTS=&quot;$GRADLE_OPTS -Xdock:name=\&quot;$APP_NAME\&quot; -Xdock:icon=$APP_HOME/media/gradle.icns&quot;
fi

# For Cygwin or MSYS, switch paths to Windows format before running java
if [ &quot;$cygwin&quot; = &quot;true&quot; -o &quot;$msys&quot; = &quot;true&quot; ] ; then
    APP_HOME=`cygpath --path --mixed &quot;$APP_HOME&quot;`
    CLASSPATH=`cygpath --path --mixed &quot;$CLASSPATH&quot;`

    JAVACMD=`cygpath --unix &quot;$JAVACMD&quot;`

    # We build the pattern for arguments to be converted via cygpath
    ROOTDIRSRAW=`find -L / -maxdepth 1 -mindepth 1 -type d 2&gt;/dev/null`
    SEP=&quot;|&quot;
    for dir in $ROOTDIRSRAW ; do
        ROOTDIRS=&quot;$ROOTDIRS$SEP$dir&quot;
    done
    ROOTDIRS=&quot;${ROOTDIRS#&quot;$SEP&quot;}"
    ROOTDIRS=`sed -e &quot;s/[\\/]/\\\\\\\\/g&quot; &lt;&lt;&lt; &quot;$ROOTDIRS&quot;`
    # Add a user-defined pattern to the cygpath arguments
    if [ &quot;$GRADLE_CYGPATTERN&quot; != &quot;&quot; ] ; then
        ROOTDIRS=&quot;$ROOTDIRS|$GRADLE_CYGPATTERN&quot;
    fi
    # Now convert the arguments - kludge to limit ourselves to /bin/sh
    i=0
    for arg in &quot;$@&quot;; do
        CHECK=`echo &quot;$arg&quot;|egrep -c &quot;^(/$|\\\\{6,$}cygwin|\\\\{6,$}java|[:[:space:]]*)$&quot;`
        CHECK2=`echo &quot;$arg&quot;|egrep -c &quot;^&quot;$ROOTDIRS&quot;$|/&quot;`
        if [ $CHECK -ne 1 -a $CHECK2 -eq 0 ] ; then
            eval `echo args$i`=`cygpath --path --mixed &quot;$arg&quot;`
        else
            eval `echo args$i`=&quot;\&quot;$arg\&quot;&quot;
        fi
        i=`expr $i + 1`
    done
    case $i in
        0) set -- ;;
        1) set -- &quot;$args0&quot; ;;
        2) set -- &quot;$args0&quot; &quot;$args1&quot; ;;
        3) set -- &quot;$args0&quot; &quot;$args1&quot; &quot;$args2&quot; ;;
        4) set -- &quot;$args0&quot; &quot;$args1&quot; &quot;$args2&quot; &quot;$args3&quot; ;;
        5) set -- &quot;$args0&quot; &quot;$args1&quot; &quot;$args2&quot; &quot;$args3&quot; &quot;$args4&quot; ;;
        6) set -- &quot;$args0&quot; &quot;$args1&quot; &quot;$args2&quot; &quot;$args3&quot; &quot;$args4&quot; &quot;$args5&quot; ;;
        7) set -- &quot;$args0&quot; &quot;$args1&quot; &quot;$args2&quot; &quot;$args3&quot; &quot;$args4&quot; &quot;$args5&quot; &quot;$args6&quot; ;;
        8) set -- &quot;$args0&quot; &quot;$args1&quot; &quot;$args2&quot; &quot;$args3&quot; &quot;$args4&quot; &quot;$args5&quot; &quot;$args6&quot; &quot;$args7&quot; ;;
        9) set -- &quot;$args0&quot; &quot;$args1&quot; &quot;$args2&quot; &quot;$args3&quot; &quot;$args4&quot; &quot;$args5&quot; &quot;$args6&quot; &quot;$args7&quot; &quot;$args8&quot; ;;
        *) die &quot;Too many arguments&quot; ;;
    esac
fi

exec &quot;$JAVACMD&quot; $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS &quot;-Dorg.gradle.appname=$APP_BASE_NAME&quot; -classpath &quot;$CLASSPATH&quot; org.gradle.wrapper.GradleWrapperMain &quot;$@&quot;